// GENERATED by scripts/vendor-canvas.ts from engines/canvas/recorders/ts/src/cssColor.ts @ 23709a8042ed — do not edit here.
// Bump the submodule and run `bun run vendor:canvas`; `bun run check:canvas-ops` fails when this copy is stale.
// The CSS color parser — the TypeScript twin of core/include/anycanvas/css_color.h: the same grammar,
// the same name table, float32 emulated op for op (Math.fround, in the header's order), so both give
// the same bits; tests/golden/colors holds them equal (tests/ts/cssColor.test.ts). Standalone: no
// imports, no DOM, nothing at the top level but const declarations (the SDK vendors this file, and
// its bundler drops top-level side effects).
//
// Grammar (the header has the full text): #rgb #rgba #rrggbb #rrggbbaa · rgb() / rgba() · hsl() /
// hsla() · the 148 CSS Color 4 names · transparent · clear (the ONE non-CSS alias, = transparent).
// Case-insensitive, surrounding ASCII whitespace ignored; a string stops at an embedded NUL, like the
// C string the header reads. Numbers are CSS number tokens (nan / inf / hex reject), units only
// deg / rad / grad / turn, out-of-range values clamp. Anything else is null.

/** A color: straight float32 RGBA, 0..1. */
export interface CssRgba { r: number, g: number, b: number, a: number }

/** The named colors as 0xRRGGBBAA: the 148 CSS Color 4 names, transparent and clear (= transparent). */
export const CSS_COLOR_NAMES: Readonly<Record<string, number>> = {
  aliceblue: 0xf0f8ffff, antiquewhite: 0xfaebd7ff, aqua: 0x00ffffff, aquamarine: 0x7fffd4ff, azure: 0xf0ffffff, beige: 0xf5f5dcff,
  bisque: 0xffe4c4ff, black: 0x000000ff, blanchedalmond: 0xffebcdff, blue: 0x0000ffff, blueviolet: 0x8a2be2ff, brown: 0xa52a2aff,
  burlywood: 0xdeb887ff, cadetblue: 0x5f9ea0ff, chartreuse: 0x7fff00ff, chocolate: 0xd2691eff, coral: 0xff7f50ff, cornflowerblue: 0x6495edff,
  cornsilk: 0xfff8dcff, crimson: 0xdc143cff, cyan: 0x00ffffff, darkblue: 0x00008bff, darkcyan: 0x008b8bff, darkgoldenrod: 0xb8860bff,
  darkgray: 0xa9a9a9ff, darkgreen: 0x006400ff, darkgrey: 0xa9a9a9ff, darkkhaki: 0xbdb76bff, darkmagenta: 0x8b008bff, darkolivegreen: 0x556b2fff,
  darkorange: 0xff8c00ff, darkorchid: 0x9932ccff, darkred: 0x8b0000ff, darksalmon: 0xe9967aff, darkseagreen: 0x8fbc8fff, darkslateblue: 0x483d8bff,
  darkslategray: 0x2f4f4fff, darkslategrey: 0x2f4f4fff, darkturquoise: 0x00ced1ff, darkviolet: 0x9400d3ff, deeppink: 0xff1493ff, deepskyblue: 0x00bfffff,
  dimgray: 0x696969ff, dimgrey: 0x696969ff, dodgerblue: 0x1e90ffff, firebrick: 0xb22222ff, floralwhite: 0xfffaf0ff, forestgreen: 0x228b22ff,
  fuchsia: 0xff00ffff, gainsboro: 0xdcdcdcff, ghostwhite: 0xf8f8ffff, gold: 0xffd700ff, goldenrod: 0xdaa520ff, gray: 0x808080ff,
  green: 0x008000ff, greenyellow: 0xadff2fff, grey: 0x808080ff, honeydew: 0xf0fff0ff, hotpink: 0xff69b4ff, indianred: 0xcd5c5cff,
  indigo: 0x4b0082ff, ivory: 0xfffff0ff, khaki: 0xf0e68cff, lavender: 0xe6e6faff, lavenderblush: 0xfff0f5ff, lawngreen: 0x7cfc00ff,
  lemonchiffon: 0xfffacdff, lightblue: 0xadd8e6ff, lightcoral: 0xf08080ff, lightcyan: 0xe0ffffff, lightgoldenrodyellow: 0xfafad2ff, lightgray: 0xd3d3d3ff,
  lightgreen: 0x90ee90ff, lightgrey: 0xd3d3d3ff, lightpink: 0xffb6c1ff, lightsalmon: 0xffa07aff, lightseagreen: 0x20b2aaff, lightskyblue: 0x87cefaff,
  lightslategray: 0x778899ff, lightslategrey: 0x778899ff, lightsteelblue: 0xb0c4deff, lightyellow: 0xffffe0ff, lime: 0x00ff00ff, limegreen: 0x32cd32ff,
  linen: 0xfaf0e6ff, magenta: 0xff00ffff, maroon: 0x800000ff, mediumaquamarine: 0x66cdaaff, mediumblue: 0x0000cdff, mediumorchid: 0xba55d3ff,
  mediumpurple: 0x9370dbff, mediumseagreen: 0x3cb371ff, mediumslateblue: 0x7b68eeff, mediumspringgreen: 0x00fa9aff, mediumturquoise: 0x48d1ccff, mediumvioletred: 0xc71585ff,
  midnightblue: 0x191970ff, mintcream: 0xf5fffaff, mistyrose: 0xffe4e1ff, moccasin: 0xffe4b5ff, navajowhite: 0xffdeadff, navy: 0x000080ff,
  oldlace: 0xfdf5e6ff, olive: 0x808000ff, olivedrab: 0x6b8e23ff, orange: 0xffa500ff, orangered: 0xff4500ff, orchid: 0xda70d6ff,
  palegoldenrod: 0xeee8aaff, palegreen: 0x98fb98ff, paleturquoise: 0xafeeeeff, palevioletred: 0xdb7093ff, papayawhip: 0xffefd5ff, peachpuff: 0xffdab9ff,
  peru: 0xcd853fff, pink: 0xffc0cbff, plum: 0xdda0ddff, powderblue: 0xb0e0e6ff, purple: 0x800080ff, rebeccapurple: 0x663399ff,
  red: 0xff0000ff, rosybrown: 0xbc8f8fff, royalblue: 0x4169e1ff, saddlebrown: 0x8b4513ff, salmon: 0xfa8072ff, sandybrown: 0xf4a460ff,
  seagreen: 0x2e8b57ff, seashell: 0xfff5eeff, sienna: 0xa0522dff, silver: 0xc0c0c0ff, skyblue: 0x87ceebff, slateblue: 0x6a5acdff,
  slategray: 0x708090ff, slategrey: 0x708090ff, snow: 0xfffafaff, springgreen: 0x00ff7fff, steelblue: 0x4682b4ff, tan: 0xd2b48cff,
  teal: 0x008080ff, thistle: 0xd8bfd8ff, tomato: 0xff6347ff, turquoise: 0x40e0d0ff, violet: 0xee82eeff, wheat: 0xf5deb3ff,
  white: 0xffffffff, whitesmoke: 0xf5f5f5ff, yellow: 0xffff00ff, yellowgreen: 0x9acd32ff,
  transparent: 0x00000000, clear: 0x00000000,
}

// float32 arithmetic: every operation of the header, rounded as it rounds (a double op on two float32
// operands, rounded once to float32, is the float32 op).
const f = Math.fround
const T13 = f(1 / 3), T16 = f(1 / 6), T23 = f(2 / 3), PI = f(3.14159265), GRAD = f(0.9)

// ASCII only, by char code (no toLowerCase / trim: they know Unicode, the header does not).
const isSpace = (c: number): boolean => c === 32 || (c >= 9 && c <= 13)
const isDigit = (c: number): boolean => c >= 48 && c <= 57
const lower = (c: number): number => c >= 65 && c <= 90 ? c + 32 : c
const isLetter = (c: number): boolean => { const l = lower(c); return l >= 97 && l <= 122 }
const hexNibble = (c: number): number => {
  const l = lower(c)
  return l >= 48 && l <= 57 ? l - 48 : l >= 97 && l <= 102 ? l - 87 : -1
}
const equalsLower = (s: string, at: number, n: number, word: string): boolean => {
  if (n !== word.length) return false
  for (let i = 0; i < n; i++) if (lower(s.charCodeAt(at + i)) !== word.charCodeAt(i)) return false
  return true
}

// The CSS number token at s[at..end): [+-]? (digits (. digits*)? | . digits) ([eE] [+-]? digits)? → its
// length, 0 when there is none.
const numberLength = (s: string, at: number, end: number): number => {
  let i = at
  if (i < end && (s.charCodeAt(i) === 43 || s.charCodeAt(i) === 45)) i++
  let intDigits = 0, fracDigits = 0
  while (i < end && isDigit(s.charCodeAt(i))) { i++; intDigits++ }
  if (i < end && s.charCodeAt(i) === 46) {
    let j = i + 1
    while (j < end && isDigit(s.charCodeAt(j))) { j++; fracDigits++ }
    if (intDigits > 0 || fracDigits > 0) i = j
  }
  if (intDigits === 0 && fracDigits === 0) return 0
  if (i < end && (s.charCodeAt(i) === 101 || s.charCodeAt(i) === 69)) {
    let j = i + 1
    if (j < end && (s.charCodeAt(j) === 43 || s.charCodeAt(j) === 45)) j++
    if (j < end && isDigit(s.charCodeAt(j))) {
      while (j < end && isDigit(s.charCodeAt(j))) j++
      i = j
    }
  }
  return i - at
}

interface Arg { v: number, percent: boolean }

// The arguments between the parentheses, s[at..end): 3 or 4 numbers with a % flag each, or null.
const parseArgs = (s: string, at: number, end: number): Arg[] | null => {
  const out: Arg[] = []
  let i = at
  while (i < end) {
    while (i < end && (isSpace(s.charCodeAt(i)) || s.charCodeAt(i) === 44 || s.charCodeAt(i) === 47)) i++
    if (i >= end) break
    const len = numberLength(s, i, end)
    if (len === 0 || len >= 64) return null   // the header's stack buffer
    let v = f(parseFloat(s.slice(i, i + len)))
    i += len
    let percent = false
    if (i < end && s.charCodeAt(i) === 37) {
      percent = true
      i++
    } else if (i < end && isLetter(s.charCodeAt(i))) {
      const u = i
      while (i < end && isLetter(s.charCodeAt(i))) i++
      const ul = i - u
      if (equalsLower(s, u, ul, "deg")) {
        // degrees: the number as it is
      } else if (equalsLower(s, u, ul, "rad")) {
        v = f(v * 180)
        v = f(v / PI)
      } else if (equalsLower(s, u, ul, "turn")) {
        v = f(v * 360)
      } else if (equalsLower(s, u, ul, "grad")) {
        v = f(v * GRAD)
      } else {
        return null
      }
    }
    if (!Number.isFinite(v)) return null
    if (out.length === 4) return null
    out.push({ v, percent })
  }
  return out.length >= 3 ? out : null
}

const clamp01 = (v: number): number => v < 0 ? 0 : v > 1 ? 1 : v

const hueToRgb = (p: number, q: number, t: number): number => {
  if (t < 0) t = f(t + 1)
  if (t > 1) t = f(t - 1)
  const d = f(q - p)
  if (t < T16) return f(p + f(f(d * 6) * t))
  if (t < 0.5) return q
  if (t < T23) return f(p + f(f(d * f(T23 - t)) * 6))
  return p
}

const fromBytes = (r: number, g: number, b: number, a: number): CssRgba => ({ r: f(r / 255), g: f(g / 255), b: f(b / 255), a: f(a / 255) })

/** A CSS color → straight float32 RGBA, or null when `input` is not a color. */
export const parseCssColor = (input: string): CssRgba | null => {
  if (typeof input !== "string") return null
  const nul = input.indexOf("\0")
  const s = nul < 0 ? input : input.slice(0, nul)
  let b = 0, e = s.length
  while (b < e && isSpace(s.charCodeAt(b))) b++
  while (e > b && isSpace(s.charCodeAt(e - 1))) e--
  const n = e - b
  if (n === 0) return null

  if (s.charCodeAt(b) === 35) {   // #
    const digits = n - 1
    if (digits !== 3 && digits !== 4 && digits !== 6 && digits !== 8) return null
    const v: number[] = []
    for (let i = 0; i < digits; i++) {
      const h = hexNibble(s.charCodeAt(b + 1 + i))
      if (h < 0) return null
      v.push(h)
    }
    return digits <= 4
      ? fromBytes(v[0] * 17, v[1] * 17, v[2] * 17, digits === 4 ? v[3] * 17 : 255)
      : fromBytes(v[0] * 16 + v[1], v[2] * 16 + v[3], v[4] * 16 + v[5], digits === 8 ? v[6] * 16 + v[7] : 255)
  }

  const paren = s.indexOf("(", b)
  if (paren >= 0 && paren < e && s.charCodeAt(e - 1) === 41) {
    const args = parseArgs(s, paren + 1, e - 1)
    if (!args) return null
    const alpha = args.length === 4 ? clamp01(args[3].percent ? f(args[3].v / 100) : args[3].v) : 1
    const fnLen = paren - b
    if (equalsLower(s, b, fnLen, "rgb") || equalsLower(s, b, fnLen, "rgba")) {
      const channel = (x: Arg): number => clamp01(x.percent ? f(x.v / 100) : f(x.v / 255))
      return { r: channel(args[0]), g: channel(args[1]), b: channel(args[2]), a: alpha }
    }
    if (equalsLower(s, b, fnLen, "hsl") || equalsLower(s, b, fnLen, "hsla")) {
      let h = args[0].v % 360   // fmodf: exact, the sign of the dividend
      if (h < 0) h = f(h + 360)
      h = f(h / 360)
      const sat = clamp01(f(args[1].v / 100))
      const l = clamp01(f(args[2].v / 100))
      if (sat <= 0) return { r: l, g: l, b: l, a: alpha }
      const q = l < 0.5 ? f(l * f(1 + sat)) : f(f(l + sat) - f(l * sat))
      const p = f(f(2 * l) - q)
      return {
        r: clamp01(hueToRgb(p, q, f(h + T13))),
        g: clamp01(hueToRgb(p, q, h)),
        b: clamp01(hueToRgb(p, q, f(h - T13))),
        a: alpha,
      }
    }
    return null
  }

  // A name: looked up only when it can be one ('lightgoldenrodyellow' is the longest, 20).
  if (n > 20) return null
  let name = ""
  for (let i = b; i < e; i++) name += String.fromCharCode(lower(s.charCodeAt(i)))
  if (!Object.prototype.hasOwnProperty.call(CSS_COLOR_NAMES, name)) return null
  const v = CSS_COLOR_NAMES[name]
  return fromBytes(v >>> 24, (v >>> 16) & 255, (v >>> 8) & 255, v & 255)
}

/** A float channel → a byte, as the header's toByte: float32, clamp (NaN → 0), round half up (0.5 → 128). */
export const cssToByte = (v: number): number => {
  const x = f(v)
  if (!(x > 0)) return 0
  if (x >= 1) return 255
  const s = f(x * 255)
  return Math.floor(f(s + 0.5))
}

/** 0xRRGGBBAA (unsigned). */
export const cssRgba8 = (c: CssRgba): number =>
  ((cssToByte(c.r) << 24) | (cssToByte(c.g) << 16) | (cssToByte(c.b) << 8) | cssToByte(c.a)) >>> 0

/** '#rrggbbaa', lower-case. */
export const cssHex8 = (c: CssRgba): string => "#" + cssRgba8(c).toString(16).padStart(8, "0")
